name: (English) Behavior Bug or Plugin Incompatibility
description: Report issues with plugin incompatibility or other behavior related issues.
body:
  - type: markdown
    attributes:
      value: |
        Before reporting an issue here, please make sure you are on the latest version of RaytraceAntiXray.

  - type: textarea
    attributes:
      label: Expected behavior
      description: What you expected to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Observed/Actual behavior
      description: What you actually saw.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps/models to reproduce
      description: This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Plugin list
      description: All plugins running on the server.
    validations:
      required: true
  - type: textarea
    attributes:
      label: RaytraceAntiXray version
      description: |
        Go to ``SERVER_FOLDER/imanity/rancha.yml`` **Copy and paste** ``spigotJarVersion`` to here
        note that *LATEST* is not a version.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Spigot version & fork name
      description: |
        Type /version to check your current spigot version and if you know what spigot fork you are using (Paper, Purpur), write it here.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Agreements
      description: Please agree to the following.
      options:
        - label: I am running the latest version of Raytrace AntiXray available.
          required: true
        - label: I have searched for and ensured there isn't already an open issue regarding this.
          required: true

  - type: textarea
    attributes:
      label: Other
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
    validations:
      required: false

