blank_issues_enabled: false
contact_links:
  - name: Imanity Discord
    url: https://go.imanity.dev/discord
    about: If you are having issues with settings or have other minor issues, come ask us on our Discord server!
